version: "3.8"

networks:
  docker_net:
    external: true

services:
  excalidraw:
    image: excalidraw/excalidraw:latest
    container_name: excalidraw
    restart: unless-stopped
    ports:
      - 3030:80
    networks:
      - docker_net
