version: "3.0"

networks:
  docker_net:
    external: true

volumes:
  config:
  books:

services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna
    volumes:
      - config:/config
      - books:/books
    ports:
      - 8083:8083
    networks:
      - docker_net
