version: '3.3'

networks:
  docker_net:
    external: true

volumes:
  trainingData:
  extraConfigs:
  customFiles:
  # logs:

services:
  stirling-pdf:
    image: frooodle/s-pdf:latest
    container_name: stirling-pdf
    restart: unless-stopped
    ports:
      - 8088:8080
    volumes:
      - trainingData:/usr/share/tessdata # Required for extra OCR languages
      - extraConfigs:/configs
      - customFiles:/customFiles/
      # - logs:/logs/
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=false
      - LANGS=en_US
    networks:
      - docker_net
